name: Release

on:
  workflow_dispatch:
    inputs:
      beta:
        type: boolean
        description: Beta
      dry-run:
        type: boolean
        description: Dry run

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    if: github.event.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: actions/cache@v2
        with:
          path: ~/.venv
          key: poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-
      - name: Install dependencies
        run: |
          pip install -U poetry
          poetry config virtualenvs.in-project true
          poetry install
      - name: Run semantic release
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          poetry run semantic-release publish -v DEBUG ${{ github.event.inputs.beta == 'true' && '--prerelease' || '' }} ${{ github.event.inputs.dry-run == 'true' && '--noop' || '' }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY_USERNAME: __token__
          REPOSITORY_PASSWORD: ${{ secrets.PYPI_TOKEN }}
